<a href="https://colab.research.google.com/github/Onestringlab/osl_statistik/blob/main/2_Apa_itu_Ukuran_Penyebaran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import library numpy**

In [1]:
import numpy as np

**Membuat Data**

In [2]:
# generate 30 data bilangan real
data = np.random.randn(30)
data

array([-0.20181808,  0.56644081, -0.5385213 ,  0.95774588,  0.97635735,
       -1.0941052 ,  0.93006759,  0.4492942 ,  0.19985695,  0.66997106,
        0.14827642,  1.2728451 , -0.11812149,  0.60403548, -0.40400818,
        0.62219441,  0.46435442,  0.27383479, -0.89920297, -0.05828149,
        0.74119153, -0.55061788, -0.68031783,  1.54683908, -1.66209298,
        1.20524697,  0.32575178, -0.07868015,  0.53524161, -0.01932291])

In [3]:
# mengurutkan data
data = np.sort(data)
data

array([-1.66209298, -1.0941052 , -0.89920297, -0.68031783, -0.55061788,
       -0.5385213 , -0.40400818, -0.20181808, -0.11812149, -0.07868015,
       -0.05828149, -0.01932291,  0.14827642,  0.19985695,  0.27383479,
        0.32575178,  0.4492942 ,  0.46435442,  0.53524161,  0.56644081,
        0.60403548,  0.62219441,  0.66997106,  0.74119153,  0.93006759,
        0.95774588,  0.97635735,  1.20524697,  1.2728451 ,  1.54683908])

**1. Range**<br>
Menghitung selisih antara data terbesar dan data terkecil
$$range = max(data) - min(data)$$

In [4]:
# menghitung range
np.max(data) - np.min(data)

3.2089320572772344

**2. Quartile** <br>
Quartile membagi urutan-urutan data menjadi 4 bagian yang sama

In [5]:
# Quartile Pertama
Q1 = np.percentile(data,25)
Q1

-0.18089393017739763

In [6]:
# Quartile Kedua
Q2 = np.percentile(data,50)
Q2

0.2997932878575289

In [7]:
# Quartile Ketiga
Q3 = np.percentile(data,75)
Q3

0.6580268993082843

**Interquatile Range**
$$IQR = Q_3 - Q_1$$

In [8]:
IQR = Q3 - Q1
IQR

0.8389208294856819

**3. Variance**<br>
Menunjukkan sejauh mana data tersebar dari rata-rata<br>
Rumus Variance untuk populasi
$$\sigma^2 = \frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}$$

Rumus Variance untuk sampel
$$S^2 = \frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}$$

In [9]:
# generate 100 data bilangan real
populasi = np.random.randn(100)

# mengurutkan data
populasi = np.sort(populasi)

populasi

array([-2.53211626e+00, -1.98230935e+00, -1.56840010e+00, -1.50407864e+00,
       -1.43215884e+00, -1.36079405e+00, -1.31673459e+00, -1.26141567e+00,
       -1.06062988e+00, -1.06062771e+00, -9.78396710e-01, -9.77292420e-01,
       -9.64091140e-01, -9.48780367e-01, -9.24499652e-01, -9.04653064e-01,
       -8.56245634e-01, -7.67055257e-01, -7.30042060e-01, -7.01571723e-01,
       -6.95768924e-01, -6.94302445e-01, -6.94119909e-01, -6.45289676e-01,
       -6.22733420e-01, -6.01237917e-01, -5.95411061e-01, -5.87801735e-01,
       -5.86108748e-01, -5.73332169e-01, -5.40135774e-01, -4.63402257e-01,
       -4.46188339e-01, -4.21859375e-01, -3.57440395e-01, -3.32591025e-01,
       -3.30816966e-01, -3.11657057e-01, -2.83051890e-01, -2.79316128e-01,
       -2.69953269e-01, -2.38457920e-01, -2.09225580e-01, -1.79321574e-01,
       -1.65357898e-01, -1.65034083e-01, -1.61820912e-01, -1.55502134e-01,
       -7.32946941e-02, -4.87252346e-02, -4.65713333e-02, -2.78876738e-02,
       -5.62504973e-04,  

In [10]:
# generate 100 data bilangan real
sampel = np.random.choice(populasi, 20)

# mengurutkan data
sampel = np.sort(sampel)

sampel

array([-1.31673459e+00, -9.78396710e-01, -9.64091140e-01, -7.67055257e-01,
       -5.95411061e-01, -4.46188339e-01, -4.46188339e-01, -3.32591025e-01,
       -3.32591025e-01, -2.38457920e-01, -2.09225580e-01, -1.55502134e-01,
       -5.62504973e-04,  3.30052735e-01,  4.46889945e-01,  5.01100163e-01,
        6.05940466e-01,  7.56749547e-01,  9.92562992e-01,  1.06295994e+00])

**Menghitung Variance**

In [11]:
np.var(populasi)

0.6997660157012142

In [12]:
np.var(sampel)

0.43522759137818684

**4. Standar Deviasi**<br>
Standar Deviasi adalah akar dari variance<br>
Rumus standar deviasi untuk populasi

$$\sigma =\sqrt{\frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}}$$

Rumus standar deviasi untuk sampel
$$S =\sqrt{\frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}}$$


**Menghitung Standar Deviasi**


In [13]:
np.std(populasi)


0.836520182482894

In [14]:
np.std(sampel)

0.6597178119303638